name: Build and Test

on:
  push:
    branches: [ main, develop ]
    tags-ignore:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test Core
      run: dotnet test tests/CassandraProbe.Core.Tests --no-build --verbosity normal
      
    - name: Test Services
      run: dotnet test tests/CassandraProbe.Services.Tests --no-build --verbosity normal
      
    - name: Test Actions
      run: dotnet test tests/CassandraProbe.Actions.Tests --no-build --verbosity normal
      
    - name: Test Scheduling
      run: dotnet test tests/CassandraProbe.Scheduling.Tests --no-build --verbosity normal
      
    - name: Test Logging
      run: dotnet test tests/CassandraProbe.Logging.Tests --no-build --verbosity normal
      
    - name: Test CLI
      run: dotnet test tests/CassandraProbe.Cli.Tests --no-build --verbosity normal
  
  sbom:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install CycloneDX
      run: dotnet tool install --global CycloneDX
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Generate SBOM
      run: |
        # Generate JSON SBOM
        dotnet CycloneDX src/CassandraProbe.Cli/CassandraProbe.Cli.csproj -f json -o .
        # Generate XML SBOM
        dotnet CycloneDX src/CassandraProbe.Cli/CassandraProbe.Cli.csproj -f xml -o .
        
        # Debug: Show what was created
        echo "=== Current directory structure ==="
        ls -la
        
        # Move files from format directories
        if [ -d "json" ] && [ -f "json/bom.json" ]; then
          echo "Moving json/bom.json to sbom.json"
          mv json/bom.json ./sbom.json
        fi
        
        if [ -d "xml" ] && [ -f "xml/bom.xml" ]; then
          echo "Moving xml/bom.xml to sbom.xml"
          mv xml/bom.xml ./sbom.xml
        fi
        
        # Verify files exist
        echo "=== Checking for SBOM files ==="
        if [ -f "sbom.json" ]; then
          echo "✓ sbom.json exists"
        else
          echo "✗ sbom.json NOT found"
        fi
        
        if [ -f "sbom.xml" ]; then
          echo "✓ sbom.xml exists"
        else
          echo "✗ sbom.xml NOT found"
        fi
        
        # Final directory listing
        echo "=== Final directory listing ==="
        ls -la sbom.* || echo "No sbom.* files found"
    
    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sbom-latest
        path: |
          json/bom.json
          xml/bom.xml
          sbom.json
          sbom.xml
        if-no-files-found: warn
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Publish Windows
      run: dotnet publish src/CassandraProbe.Cli -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ./artifacts/windows
      
    - name: Publish Linux
      run: dotnet publish src/CassandraProbe.Cli -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -o ./artifacts/linux
      
    - name: Publish macOS (Intel)
      run: dotnet publish src/CassandraProbe.Cli -c Release -r osx-x64 --self-contained -p:PublishSingleFile=true -o ./artifacts/osx-x64
      
    - name: Publish macOS (ARM64)
      run: dotnet publish src/CassandraProbe.Cli -c Release -r osx-arm64 --self-contained -p:PublishSingleFile=true -o ./artifacts/osx-arm64
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cassandra-probe-binaries
        path: ./artifacts/